# Generated by Django 3.2.4 on 2021-07-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalindicador',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion'),
        ),
    ]
